# Github action to build, run and test a Docker image.

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Start Consul
        run: |
          docker pull wdijkerman/consul
          docker-compose up -d consul
          while [[ $(docker logs consul 2>&1 | grep 'agent: Synced node info' | wc -l) -eq 0 ]];do
            echo 'Waiting for proper boot'
            sleep 5
          done

      - name: Creating Vault Docker image
        run: docker build -t wdijkerman/vault .

      - name: Start Vault
        run: |
          docker-compose up -d vault
          sleep 5

      - name: Execute testinfra
        run: py.test -v --connection=docker --hosts=vault
